server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://192.168.2.38:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml